layout_spectrum: 0.4975851
typography_spectrum: 0.5591671
color:
  saturation: 0.8629153
  lightness: 0.4000349
  brandStrength: 0.5639434
  rhythmicContrast: 0.03139222
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Testbeto1234
